######################################################################
# Automatically generated by qmake (2.01a) Sun May 5 14:19:42 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += videodevice.h
SOURCES += main.cpp videodevice.cpp
