######################################################################
# Automatically generated by qmake (2.01a) Sun May 5 15:03:08 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test3.cpp
