######################################################################
# Automatically generated by qmake (2.01a) Sun May 5 19:25:39 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += webcam-capture.c \
    v4l2grab.c
